Dockerfile, docker-compose.yml
Was accidentally removed in https://github.com/prysmaticlabs/documentation/commit/5463e29e8433edeb6379be41db39f9328da18511
=> Add Back Docker File

docs/prysm-usage/wallet-keymanager.md
A few clarifications and updates to the wallet key manager documentation after feedback on initial version.
=> Tweaks to keymanager information.

docs/faq.md, docs/install/arm.md, docs/install/arm/bazel.md, docs/install/arm/troubleshooting.md, docs/install/lin/bazel.md, docs/install/lin/docker.md, docs/install/lin/troubleshooting.md, docs/install/linux.md, docs/install/mac.md, docs/install/mac/bazel.md, docs/install/mac/docker.md, docs/install/mac/troubleshooting.md, docs/install/troubeshooting.md, docs/install/win/bazel.md, docs/install/win/docker.md, docs/install/win/troubleshooting.md, docs/install/windows.md, docs/prysm-usage/parameters.md, docs/prysm-usage/wallet-keymanager.md, website/sidebars.json
Addresses April meeting notes, tracker issue #37
=> April meeting changes

.gitignore, docs/how-prysm-works/overview-technical.md, docs/how-prysm-works/validator-clients.md, docs/introduction/overview-technical.md
- fixes broken links to public RPC server page
=> Fix link to gRPC docs

docs/install/arm.md, docs/install/linux.md, docs/install/mac.md
This PR updates system requirements to specify OS X 10.14 or greater
=> Require Mac OS X 10.14+

docs/install/arm/activating-a-validator.md, docs/install/lin/activating-a-validator.md, docs/install/mac/activating-a-validator.md, docs/install/win/activating-a-validator.md
Added numbered headers for Step 3a/b
Ensured consistent use of ARM64 (vs ARM)
=> Numbered headers for Step 3a/b, consistent ARM64

docs/prysm-usage/slasher.md, website/sidebars.json
Mostly addresses #59 but also need an update to list available flags: https://docs.prylabs.network/docs/prysm-usage/parameters/
=> Slasher 1-pager

docs/install/lin/docker.md, docs/install/mac/docker.md, docs/install/win/docker.md
Adjusted debugging notes. Left the port 13000 notes in place as pragmatics is working on a change for this in the next PR
=> Debug note fixes

docs/prysm-usage/p2p-host-ip.md
=> Broken slug

docs/install/lin/docker.md
Point to the correct page (https://docs.prylabs.network/docs/how-prysm-works/architecture-overview/)
=> Fix broken link

docs/prysm-usage/p2p-host-ip.md
As suggested by @nisdas and "pragmatics" in Discord:
=> Added section on verfiying p2p host ip settings

docs/install/win/docker.md, docs/install/windows.md
this PR goes through the windows documentation and makes sure the commands match each other on the same page.
=> Make windows commands consistent

docs/install/arm/activating-a-validator.md, docs/install/mac/activating-a-validator.md
=> typo in path

docs/faq.md, docs/install/arm/activating-a-validator.md, docs/install/lin/activating-a-validator.md, docs/install/mac/activating-a-validator.md, docs/install/win/activating-a-validator.md
Related: https://github.com/prysmaticlabs/prysm/pull/5784
=> Docs for `validator accounts status` command

docs/install/arm/activating-a-validator.md, docs/install/lin/activating-a-validator.md, docs/install/mac/activating-a-validator.md, docs/install/win/activating-a-validator.md
small adjustments to validator activation pages
=> quick cleanup

docs/install/arm/activating-a-validator.md, docs/install/lin/activating-a-validator.md, docs/install/mac/activating-a-validator.md
=> Amend #108

docs/install/arm/bazel.md, docs/install/lin/bazel.md, docs/install/lin/docker.md, docs/install/mac/bazel.md, docs/install/mac/docker.md, docs/install/win/docker.md
Adds system specs to each page and updates :latest tags to :stable. Resolves #103 and #120
=> system specs and tags modified

docs/prysm-usage/slasher.md
Updated slasher commands, also resolves #93. I added the `--network="host" ` flag to the linux command as well, is this correct?
=> updated commands

website/docs/introduction/ethereum-2.0.md
Issue #158 
Updated number of shards from 1024 to 64 shards
=> Update ethereum-2.0.md 

website/static/assets/grafana-dashboards/big_amount_validators.json, website/static/assets/grafana-dashboards/small_amount_validators.json
Fix a link in the README panel + add Prometheus as the datasource for every panel and set id to null (this is required to import the dashboard through API in response to https://github.com/GuillaumeMiralles/prysm-grafana-dashboard/issues/3)
=> Update dashboards 

website/package-lock.json, website/package.json
Reverts prysmaticlabs/documentation#169 which causes the getting started page not to exist.
=> Revert "Update dependency @docusaurus/preset-classic to v2.0.0-alpha.58"

website/docs/how-prysm-works/overview-technical.md
=> Update shard number from 1024 to 64

website/docs/prysm-usage/wallet-keymanager.md
fixing issue #203 to redirect link to correct site https://docs.prylabs.network/docs/wallet/introduction
=> Update wallet-keymanager.md - fixing link to wallets and accounts

website/static/assets/grafana-dashboards/small_amount_validators.json
- Updates small_ammounts_validaor.json to most recent version which includes a minor bugfix
=> updated small_ammount_validator.json

website/docs/install/lin/activating-a-validator.md
Added a S to validator on line 135
=> Typo correction for checking validator status with prysm.sh

website/docs/testnet/medalla.md
Update validator docker commands to be more clear.
=> Add In Appropriate Volumes and Container Names

website/docs/prysm-usage/monitoring/currency-converter.md
Forgot in previous PR to include the slasher into this documentation.
Fix proposed by ncitron
=> Add slasher into prometheus.yml file content

website/docs/wallet/exiting-a-validator.md, website/sidebars.json
This reverts commit 64345fae4531d2be606d086c3fe74d2763f25db4.
=> Revert "Revert "Documentation for voluntary exits""

.github/workflows/link-checker.yml, website/docs/how-prysm-works/beacon-node.md, website/docs/introduction/overview-technical.md, website/docs/prysm-usage/monitoring/grafana-dashboard.md, website/docusaurus.config.js, website/package-lock.json, website/package.json, website/src/theme/Footer/index.js, website/src/theme/Footer/styles.module.css, website/src/theme/Navbar/index.js, website/src/theme/Navbar/styles.module.css
Reverts prysmaticlabs/documentation#236
=> Revert "Docusaurus link checker"

website/docs/testnet/spadina.md, website/sidebars.json
This PR adds documentation to join the Spadina testnet
=> Spadina Testnet Documentation

website/docs/testnet/zinken.md, website/sidebars.json
This PR includes documentation to join Zinken: the new multiclient testnet
=> Zinken Testnet Documentation

website/docs/testnet/zinken.md
=> Add Warning to Zinken Docs

website/docs/wallet/ethdo.md, website/sidebars.json
This PR includes docs for using ethdo with Prysm
=> Include Documentation for Ethdo Wallet Integration

website/docs/contribute/contribution-guidelines.md, website/docs/install/install-with-bazel.md, website/docs/install/install-with-docker.md, website/docs/install/install-with-script.md, website/docs/install/linux.md, website/docs/prysm-usage/parameters.md, website/docs/prysm-usage/running-a-validator.md, website/docs/testnet/medalla.md, website/docs/testnet/spadina.md, website/docs/testnet/zinken.md, website/docs/wallet/deterministic.md, website/docs/wallet/ethdo.md, website/docs/wallet/exiting-a-validator.md, website/docs/wallet/nondeterministic.md, website/docs/wallet/remote.md
This PR renames all mentions of accounts-v1 and accounts-v2 to simply `accounts`. It removes the mentions of deprecated parameters, adds instructions to accept terms of use
=> Update for Beta.0 Release

website/docs/faq.md, website/docs/getting-started.md, website/docs/install/install-with-bazel.md, website/docs/install/install-with-docker.md, website/docs/install/install-with-script.md, website/docs/mainnet/joining-eth2.md, website/docs/prysm-usage/parameters.md, website/docs/prysm-usage/web-interface.md, website/docs/wallet/deterministic.md, website/docs/wallet/ethdo.md, website/docs/wallet/introduction.md, website/docs/wallet/nondeterministic.md, website/docs/wallet/remote.md
=> Warn Users Prysm is Not Yet Mainnet Ready

website/docs/getting-started.md, website/docs/prysm-usage/staying-up-to-date.md, website/docusaurus.config.js, website/sidebars.json
This PR includes documentation on how to stay updated with Prysm, adding details of our Discord and mailing list
=> Docs on Keeping Prysm Updated

website/static/assets/grafana-dashboards/big_amount_validators.json
Alert "process down" was always triggered => fixed
=> Fix bug in alerts in grafana dashboard

website/docs/install/install-with-script.md, website/docs/prysm-usage/eth1-nodes.md, website/docs/prysm-usage/parameters.md, website/docs/prysm-usage/staying-up-to-date.md
This PR is mean going through the docs and fixing what can be improved, and updating the beacon node flags documentation. 
Notable changes: 
- Add alchemy to 3rd party eth1.
- Add new beacon node flags and make p2p category.
- Small fixes
Part of: https://github.com/prysmaticlabs/prysm/issues/7903
=> Polish and update beacon node flags

website/docs/prysm-usage/staying-up-to-date.md, website/docusaurus.config.js
This PR includes documentation on how to securely update and downgrade the software, including information on minor patches and minor version bumps and how to safely rollback databases.
=> Docs on Upgrading and Downgrading Prysm Securely

website/docs/faq.md
This PR revamps our FAQ with brand new question/answer pairs that can be more helpful to current users of Prysm
=> Revamp FAQ With New Questions

website/docs/prysm-usage/is-everything-fine.md
Deposited phase for the validator added and the correct info msg
=> Deposited phase added in documentation

website/docs/install/install-with-bazel.md, website/docs/mainnet/joining-eth2.md, website/docs/testnet/pyrmont.md, website/docs/wallet/exiting-a-validator.md
Resolves #188 resolves #258 resolves #189, this PR adds config release when needed as well as the required dependencies to build from source in our instructions
=> Add Release Config and Dependencies Instructions for Building From Source

website/docs/prysm-usage/eth1-nodes.md
No tracking issue, but overrides #220
=> Add Multi-OS Instructions to Running ETH1 Nodes

website/docs/prysm-usage/parameters.md
This updates the peer count value in our docs site to be inline with the current release in Prysm.
=> Update Peer Count

website/docs/prysm-usage/eth1-nodes.md
Documentation for functionality of https://github.com/prysmaticlabs/prysm/pull/8075
=> Documentation for eth1 endpoint authorization

website/docs/prysm-usage/slasher.md, website/docs/wallet/slashing-protection.md
This adds documentation for our new slasher implementation, which is due for release within the next week and a half
=> Add Optimized Slasher Documentation

website/docs/advanced/beacon_node_api.md, website/docs/advanced/migrating-keys.md, website/sidebars.json
First draft of the Migrating keys documentation. This also includes the update to the sidebar to include the new Advanced use section
=> Migrating keys first draft, with sidebars update.

website/docs/prysm-usage/fetchCliHelp.js, website/docs/prysm-usage/parameters.md, website/src/fetchCliHelp.js
This PR loads the help text from https://cli.prylabs.network/validator, /beacon-chain, and /client-stats and displays them in our docs parameters page for maintainability. It embeds a react component which is able to retrieve the data from the endpoint.
=> List Parameters from CLI Help Text API

website/versioned_docs/version-2.0.0/audits/phase0.md, website/versioned_docs/version-2.0.0/getting-started.md, website/versioned_docs/version-2.0.0/licenses/prysmatic-labs.md, website/versioned_sidebars/version-2.0.0-sidebars.json
Revamp the docs sidebar for Prysm v2 to be a lot more user friendly and simple
=> Sidebar Revamp for V2

website/docs/advanced/migrating-keys.md
passwor -> password
Noticed while reading the docs.  Thanks all!
=> Small typo fix

website/versioned_docs/version-2.0.3/install/install-with-bazel.md, website/versioned_docs/version-2.0.3/install/install-with-docker.md, website/versioned_docs/version-2.0.3/install/install-with-script.md
This was missed in for our v2.0.3 version in #384 .
=> Update Links for v2.0.3 as well

website/versioned_docs/version-2.0.0/devtools/api-middleware.md
Adds new fields to the definition of `Endpoint` struct.
=> Add `DELETE` fields to API Middleware

website/versioned_docs/version-2.0.6/prysm-usage/individual-validator-monitoring.md
=> Update monitoring headers

website/docs/prysm-usage/checkpoint-sync.md, website/sidebars.json
This PR adds documentation for the Checkpoint Sync feature, currently in review at https://github.com/prysmaticlabs/prysm/pull/10335
=> checkpoint sync doc

website/docs/execution-node/fee-recipient.md
This PR revises our Fee Recipient doc.
Metadoc: https://www.notion.so/prysmaticlabs/Metadoc-Fee-Recipient-afbe2d78e9944646a9aadc1c13645860
Preview: https://deploy-preview-420--prysmdocs.netlify.app/docs/next/execution-node/fee-recipient/
=> Fee Recipient Revision

website/docs/devtools/end-to-end.md, website/versioned_docs/version-2.1.0/devtools/end-to-end.md
- Added a `Testing features` section
- Removed differences between doc versions
=> Better E2E docs

website/docs/execution-node/fee-recipient.md, website/versioned_docs/version-2.1.0/execution-node/fee-recipient.md
with the current release of 2.1.2 the fix is in an we can remove this warning.
=> fee-recipient: remove warning

website/docs/execution-node/fee-recipient.md, website/versioned_docs/version-2.1.0/execution-node/fee-recipient.md
Adding examples for fee recipient config.
=> Fee-Recipient Config Examples

website/docs/install/install-with-script.md
Removing this guidance until https://github.com/prysmaticlabs/prysm/pull/10692 is implemented cc @rkapka
=> removing is_optimistic guidance from vNext quickstart - not yet implemented

website/docs/troubleshooting/issues-errors.md, website/docs/wallet/slashing-protection.md, website/versioned_docs/version-2.1.0/troubleshooting/issues-errors.md, website/versioned_docs/version-2.1.0/wallet/slashing-protection.md
This PR addresses some concerns surfaced by our community members on Discord.
TODOs:
Previews:
- https://deploy-preview-464--prysmdocs.netlify.app/docs/wallet/slashing-protection
- https://deploy-preview-464--prysmdocs.netlify.app/docs/troubleshooting/issues-errors
=> Troubleshooting improvements, slashing protection questions + answers

website/docs/wallet/exiting-a-validator.md, website/versioned_docs/version-2.1.0/wallet/exiting-a-validator.md
Current doc: https://docs.prylabs.network/docs/wallet/exiting-a-validator 
Proposed revision (PR preview):  https://deploy-preview-472--prysmdocs.netlify.app/docs/wallet/exiting-a-validator
=> Simplifying validator exit instructions

website/docs/concepts/nodes-networks.md, website/docs/install/install-with-script.md, website/docs/prepare-for-merge.md
cc @terencechain and @prestonvanloon - no action required, just wanted to close the loop on the feedback you provided. Thank you again!
=> A batch of docs feedback

website/docs/security-best-practices.md, website/docs/wallet/introduction.md
Addresses https://discord.com/channels/476244492043812875/649482799992274954/994900860498882661
=> Link fixes

website/docs/wallet/slashing-protection.md
Addresses https://github.com/prysmaticlabs/documentation/issues/365
=> Slashing protection db docs bugfix

website/docs/install/install-with-script.md, website/docs/partials/_jwt-guidance-partial.md, website/docs/vNext/214-rc.md
=> 214rc fixes

website/docs/troubleshooting/issues-errors.md
addressing https://github.com/prysmaticlabs/prysm/issues/11130
=> Adding a troubleshooting tip related to account import permissions

website/docs/prepare-for-merge.md
Updating Prep for Merge with a bugfix
=> Testnet fix

website/docs/install/install-with-script.md, website/docs/monitoring/checking-status.md
Addresses https://github.com/prysmaticlabs/documentation/issues/539
=> Adding | jq for more human readable JSON output

website/docs/partials/_jwt-generation-partial.md, website/docs/partials/_multidimensional-content-controls-partial.md, website/docs/prepare-for-merge.md, website/src/components/MultiDimensionalContentWidget.js, website/src/css/custom.css, website/src/css/custom.less
1. JWT Permissions note added per @james-prysm 
2. Duplicate service warning added per @james-prysm 
3. P2P connectivity guide linked per @james-prysm 
4. Ethereum.org resources linked
5. Formatting improvements
Previews:
1. https://deploy-preview-558--prysmdocs.netlify.app/docs/install/install-with-script
2. https://deploy-preview-558--prysmdocs.netlify.app/docs/execution-node/authentication
3. https://deploy-preview-558--prysmdocs.netlify.app/docs/prepare-for-merge
=> Merge Preparation fixes

website/docs/faq.md
=> Fixing a few typos

website/docs/install/partials/_quickstart-run-beacon-node.md, website/docs/install/partials/_quickstart-run-execution-node.md, website/docs/partials/_jwt-generation-partial.md, website/docs/partials/_jwt-guidance-partial.md, website/docs/prepare-for-merge.md, website/src/components/MultiDimensionalContentWidget.js, website/src/css/custom.css, website/src/css/custom.less
Preview: https://deploy-preview-565--prysmdocs.netlify.app/docs/prepare-for-merge
=> Bending docusaurus to our will

website/docs/execution-node/configuring-for-prysm.md, website/docs/install/partials/_quickstart-intro.md, website/docs/install/partials/_quickstart-run-execution-node.md, website/docs/monitoring/checking-status.md, website/docs/partials/_multidimensional-content-controls-partial.md, website/src/css/custom.css, website/src/css/custom.less
we get this doc for free via partials :)
Previews:
- https://deploy-preview-584--prysmdocs.netlify.app/docs/execution-node/configuring-for-prysm
- https://deploy-preview-584--prysmdocs.netlify.app/docs/monitoring/checking-status
=> Dedicated execution node config guidance, improved usage of multidimensional content widget

website/docs/monitoring/checking-status.md
https://discord.com/channels/476244492043812875/560308336248225812/1014268387121184808
=> Incorporating user feedback - Status Checklist improvements

website/docs/monitoring/checking-status.md
https://discord.com/channels/476244492043812875/560308336248225812/1014277835050995735
=> Addressing sunbird's feedback

website/docs/monitoring/checking-status.md, website/docs/monitoring/partials/_status-checklist-partial.md, website/docs/troubleshooting/issues-errors.md, website/docs/troubleshooting/partials/_beacon-troubleshooting.md, website/docs/troubleshooting/partials/_execution-troubleshooting.md, website/docs/troubleshooting/partials/_generate-troubleshooting-report.md, website/src/components/GenerateTroubleshootingReportWidget.js, website/src/components/MultiDimensionalContentWidget.js, website/src/css/custom.css, website/src/css/custom.less
Preview -> https://deploy-preview-601--prysmdocs.netlify.app/docs/troubleshooting/issues-errors
=> Troubleshooting vNext

website/docs/install/install-with-docker.md
https://github.com/prysmaticlabs/documentation/issues/611
=> Incorporating user feedback RE `--rpc-host`

website/docs/execution-node/fee-recipient.md
Goals:
- Progressively disclose complexity
- Pull the happy path up top
- Visually simplify the config details
- Reduce repetition
Preview: https://deploy-preview-613--prysmdocs.netlify.app/docs/execution-node/fee-recipient
=> Fee Recipient - simplification

website/docs/troubleshooting/partials/_execution-troubleshooting.md
Addresses https://github.com/prysmaticlabs/documentation/issues/630
=> Geth troubleshooting entry addition - `Beacon client online, but never received consensus updates` 

website/docs/monitoring/partials/_status-checklist-partial.md
Addresses https://github.com/prysmaticlabs/documentation/issues/648
=> Addressing #648 - `geth attach` syntax (IPC vs HTTP)

website/docs/prysm-usage/slasher.md
Could also instead link to a commit specifically so the link doesn't break again on refactors (left as a comment suggestion so yall can pick a preferred approach)
=> Fix broken link to slasher code

website/docs/advanced/proof-of-stake-devnet.md
Added a bit randomly.. please fix, or add the code inline. Not sure what was the original intent, but the code/link is also missing from the original blog post.
=> Added missing link

website/docs/install/partials/_quickstart-run-validator.md
=> Fixed wrong path in docs command

website/docs/wallet/remote.md
=> fixing typo in web3signer

Dockerfile
This PR updates node alpine image to 15 from 11
=> Updated node to v15

Dockerfile
=> updating npm version breaking build

website/docs/getting-started.md
withdrawal link was missing from the table of contents
=>  table of contents: add withdrawals

website/docs/execution-node/fee-recipient.md, website/docs/faq.md, website/docs/getting-started.md, website/docs/how-prysm-works/keymanager-api.md, website/docs/prysm-usage/web-interface.md
Dear Prysmers,
We would like to take a moment to inform you of an important update regarding our software. After careful consideration, we have made the difficult decision to deprecate our web UI. While we understand that this news may be disappointing, please know that it was not a decision we made lightly. We recognize that many of you have been loyal users of our software and have come to rely on its features and capabilities. Please know that this decision was made with your best interests in mind. We believe that by deprecating our web UI, we can focus our efforts on the core needs of the consensus client, bringing more software that is more resilient, more maintainable, and more sustainable. 
We understand that this may cause some inconvenience and disruption, and we want to assure …
=> Notice of Deprecation: Web UI

website/docs/wallet/introduction.md, website/docs/wallet/remote.md
adding notice for full removal of the remote signer and remote wallet. 
related to https://github.com/prysmaticlabs/prysm/issues/11700
=> Remote Signer: removal notice

website/docs/wallet/exiting-a-validator.md
adding a small notice on validator exit
=>  small notice for web3signer users exiting validator

website/docs/prysm-usage/prysmctl.md, website/docs/wallet/exiting-a-validator.md
updating commands in docs
fixes #729
=> fixing docker related items for prysmctl

website/docs/concepts/nodes-networks.md, website/docs/install/install-with-bazel.md, website/docs/install/install-with-docker.md, website/docs/install/partials/_quickstart-run-beacon-node.md, website/docs/install/partials/_quickstart-run-execution-node.md, website/docs/install/partials/_quickstart-run-validator.md, website/docs/monitoring/partials/_status-checklist-partial.md, website/docs/partials/_multidimensional-content-controls-partial.md, website/docs/prysm-usage/checkpoint-sync.md, website/src/components/MultiDimensionalContentWidget.js
testnet has been deprecated we should remove it in our docs 
fixes #701
=> removing ropsten

website/docs/wallet/withdraw-validator.md
updating withdrawal documentation to clarify steps.
=> withdrawal clarifications

website/docusaurus.config.js
*noted to be updated on releases*
=> updating prysm version displayed on docs left corner

website/docs/wallet/introduction.md
comments were not removed correctly.
=> fixing bad merge

website/docs/wallet/withdraw-validator.md
fixing typo in link
fixes #758
=> fix urltypo

website/docs/wallet/withdraw-validator.md
=> updating confusing step in withdrawals document

website/docs/execution-node/configuring-for-prysm.md, website/docs/getting-started.md, website/docs/install/partials/_quickstart-intro.md, website/docs/monitoring/partials/_status-checklist-partial.md, website/docs/prepare-for-merge.md, website/sidebars.json
replacing merge doc with withdrawal doc and marking relevant parts for deprecation
=> marking merge doc for deprecation

website/docs/prysm-usage/prysmctl.md, website/docs/wallet/withdraw-validator.md
right now running prysmctl binaries isn't clear and for some users require additional steps to add permissions.
=> improve prysmctl instructions

website/docs/wallet/exiting-a-validator.md, website/docs/wallet/withdraw-validator.md
removing capella withdrawal warnings
=> updating for post capella

website/docs/wallet/exiting-a-validator.md, website/docs/wallet/withdraw-validator.md
prysmctl should be in the cmd subfolder.
fixes #771
=> fixing command

website/docs/concepts/nodes-networks.md, website/docs/install/install-with-bazel.md, website/docs/install/install-with-docker.md, website/docs/install/partials/_quickstart-run-beacon-node.md, website/docs/install/partials/_quickstart-run-execution-node.md, website/docs/partials/_multidimensional-content-controls-partial.md, website/src/components/MultiDimensionalContentWidget.js
Adds documentation for holesky testnet
Closes https://github.com/prysmaticlabs/prysm/issues/12724
=> Add holesky documentation

website/docs/wallet/exiting-a-validator.md
Many users struggle to find the secret phrase in the documentation.
=> Add tip callout to help users exit a validator

website/docs/advanced/beacon_node_api.md, website/docs/advanced/builder.md, website/docs/advanced/migrating-keys.md, website/docs/advanced/proof-of-stake-devnet.md, website/docs/advanced/switch-clients.md, website/docs/contribute/bugreports.md, website/docs/devtools/block-explorers.md, website/docs/execution-node/fee-recipient.md, website/docs/faq.md, website/docs/install/install-with-script.md, website/docs/install/partials/_quickstart-run-execution-node.md, website/docs/prysm-usage/checkpoint-sync.md, website/docs/prysm-usage/staying-up-to-date.md, website/docs/troubleshooting/partials/_generate-troubleshooting-report.md
fixes #892,#891,#890,#888,#875,#789
=> resolving some typos, broken links, and updating some outdated descriptions

website/docs/troubleshooting/partials/_beacon-troubleshooting.md
addresses issues https://github.com/prysmaticlabs/documentation/issues/891 and https://github.com/prysmaticlabs/prysm/issues/13431
=> adding in comment for trouble shooting windows time drift issue

website/docs/install/install-with-bazel.md
Fixes #928
Depends on https://github.com/prysmaticlabs/prysm/pull/13790
=> Update docker instructions

website/docs/install/install-with-bazel.md
https://github.com/prysmaticlabs/prysm/issues/14071
=> Fix bazel run command

website/docs/advanced/switch-clients.md
=> Fix broken links

website/docs/advanced/proof-of-stake-devnet.md, website/docs/devtools/net-design.md
=> chore: fix typos

website/docs/getting-started.md, website/src/components/HeaderBadgesWidget.js
been a while since the new hardfork just some simple cleanup
=> Removing new cancun notice

website/docs/wallet/web3signer.md
adding in some doc notes based on changes in upcoming prysm version
=> updating docs to include web3signer key persistence

package-lock.json, website/docs/contribute/contribution-guidelines.md
See: https://github.com/prysmaticlabs/prysm/pull/13673
=> Update contribution guidelines to match Prysm's CHANGELOG.md addition

website/docusaurus.config.js
Do not merge til v5.1.1 is live
=> Update latest Prysm version

website/docs/install/install-with-bazel.md
Update the source link to update prysm related images' tag.
=> update prysm image tag source

docs/contribute/required-reading.md, docs/reading/eth2.md
hey team , I founded broken links in `required-reading.md` and  `eth2.md` -- fixed
=> fix dead links
