OffchainLabs/prysm-documentation

- docs/activating-a-validator.md
Replaced by `--keymanager=keystore` and `--keymanageropts`.
Also introduces fixes like publishing the 13000 port in Docker and volume path in Windows.
> --keystore-path flag is deprecated

- docs/activating-a-validator.md
- docs/getting-started.md
Validator now uses keymanager; individual options are deprecated.  This updates the document to reflect the new usage.
> Update validator commands for keymanager

- docs/prysm-usage/activating-a-validator.md
This modifies the validator startup notice to be less scary, previously sounded like you'd lose everything if your beacon node wasn't synced.
> Change validator setup text to be less scary

- docs/prysm-usage/wallet-keymanager.md
Ensure that users always pull the latest version of `ethdo` rather than a specific version, by using the `@latest` tag.
> Set version of ethdo to be latest

- docs/install/lin/activating-a-validator.md
Leaving passwords in the command line is unsafe; this updates the documentation to explain how to store them on disk and reference the relevant file.
> Provide details on storing password on filesystem

- docs/reading/testnet_postmortems.md
- website/sidebars.json
This PR adds testnet postmortems as a `Readings` section in our docs portal for the community to see.
> Add Testnet Postmortems Page

- docs/install/arm/activating-a-validator.md
- docs/install/lin/activating-a-validator.md
- docs/install/mac/activating-a-validator.md
- docs/install/win/activating-a-validator.md
- docs/prysm-usage/activating-a-validator.md
See: https://github.com/prysmaticlabs/prysm/issues/5434
```
the terminal command ./prysm.sh validator accounts create --keystore-path=$HOME/validator --password= is saved in terminal history and can be retrieved easily.
it will be better to advise users to write the command ./prysm.sh validator accounts create --keystore-path=$HOME/validator and enter those values as inputs
```
This PR removes all instances of recommending setting passwords this way
> Do Not Recommend Plaintext Password As Flag

- docs/install/windows.md
Following a chat in Discord as I experienced a slight confusion following the setup guide:
SalohcinToday at 9:53 PM
Hi I'm following this guide https://docs.prylabs.network/docs/install/windows/ and after running the line in step 4, windows comes up with the following:
Starting Prysm beacon-chain --clear-db --min-sync-peers 7
2020/04/24 21:49:18 maxprocs: Leaving GOMAXPROCS=12: CPU quota undefined
time="2020-04-24 21:49:18" level=warning msg="Using default mainnet config" prefix=flags
time="2020-04-24 21:49:18" level=warning msg="This will delete your beacon chain data base stored in your data directory. Your database backups will not be removed - do you want to proceed? (Y/N)" prefix=node
>> n
I tried saying 'Y' but then the installer just exits, but now I tried with 'N' and it …
> Minor update to running prysm.h install command

- docs/install/windows.md
prysm.bat was proposed in https://github.com/prysmaticlabs/prysm/pull/5626 and behaves exactly like prysm.sh
Instructions from other OS's simply need to be modified to use Windows Paths.
> Update instructions for windows to use prysm.bat (See Issue #5624)

- docs/how-prysm-works/validator-clients.md
Updated docs to correct info about running multiple validators in a single runtime.
> Validator client functionality - Multiple Keypairs

- docs/install/lin/activating-a-validator.md
Updated prysm.sh instructions to stop using --password in the "accounts create" command and in the "Starting the validator client with prysm.sh" section.
Fixed inconsistent path for keystore.
Simplified  "Securing the validator key" with a single 'cat' command.
Better sub-headings for Steps 3 & 4
> Linux validator page improvements using keymanager

- docs/prysm-usage/activating-a-validator.md
The link to "Read the Docs" on https://prylabs.net/participate is still pointing to outdated instructions on a hidden page of the documentation: https://docs.prylabs.network/docs/prysm-usage/activating-a-validator/
This PR updates that legacy landing page to ensure that new users are getting the the most up-to-date information.
> Legacy Landing Page

- docs/prysm-usage/parameters.md
Added Slasher base & Debug flags
Closes #59
@allsilent
Small find: the description of the --p2p-host-ip flag on the shared flags section of the Running Prysm page is accidentally a copy of the —p2p-host-dns flag right below it. Think the ip one should read differently. In that same section, the descriptions for —max-goroutines and —log-file are flipped.
> Add Slasher Flags & minor fix

- docs/install/arm/activating-a-validator.md
- docs/install/lin/activating-a-validator.md
- docs/install/mac/activating-a-validator.md
- docs/install/win/activating-a-validator.md
- docs/install/windows.md
- docs/prysm-usage/p2p-host-ip.md
- docs/prysm-usage/parameters.md
- docs/prysm-usage/slasher.md
The use of the --password flag should not be reccommended as this may result in passwords being logged to command history 
related #36
> Removed --password from all validator commands

- docs/install/arm/bazel.md
- docs/install/lin/activating-a-validator.md
- docs/install/lin/bazel.md
- docs/install/lin/docker.md
- docs/install/mac/activating-a-validator.md
- docs/install/mac/bazel.md
- docs/install/mac/docker.md
- docs/install/win/activating-a-validator.md
- docs/install/win/docker.md
- docs/prysm-usage/p2p-host-ip.md
Only TCP port 13000 was documented as being required for p2p.  discv5 uses UDP/12000 for discovery. Docker, port forwarding & firewall instructions updated to reflect this.
closes #60
> Add instructions to allow udp/12000

- docs/contribute/contribution-guidelines.md
Some users have been wanting to contribute to the Prysm codebase but are a loss at which IDEs have bazel support built in or how to enable it
> Recommend Bazel IDEs

- docs/contribute/contribution-guidelines.md
- docs/how-prysm-works/ethereum-2.0-public-api.md
Our public APIs page was super outdated, and several users have come forth with great contributions to the api for eth2 despite us having to explain the whole contribution process to them first. This PR updates the page with instructions on using Bazel and how to implement the API changes in Prysm.
> Add Instructions for Public API Contributions

- docs/prysm-usage/parameters.md
This PR fix the name of the `--beacon-rpc-provider` that was previously wrong in the doc with `--beacon-rpc-server`
> Fixing parameters name --beacon-rpc-provider

- docs/prysm-usage/grafana-dashboard.md
1. Since the option to `--enable-account-metrics` is now by default, we can remove this step from the dashboard setup guide.
2.  I changed the metric to retrieve in Prometheus for the validator with `validator_statuses` that will be shown faster than the `validator_balance` that takes several minutes
> Update to adjust with alpha 9

- docs/prysm-usage/eth1-nodes.md
We now recommend users to run their own eth1 nodes to be able to participate in eth2. This PR adds a new page to display how to use a third party provider or your own node.
> Recommend Ways of Running ETH1 Nodes

- docs/contribute/contribution-guidelines.md
This PR updates our contribution guidelines on ways to build and test Prysm using pure Go 1.14.x
> Update Contribution Guidelines for Pure Go

- website/docs/prysm-usage/secure-grpc.md
- website/sidebars.json
This PR adds much requested documentation for setting up secure gRPC connections for beacon node <> validator interactions. It includes instructions on how to generate self-signed certificates and also how to use let's encrypt to reliably renew TLS certificates.
> Instructions for How to Setup Secure gRPC Connections

- website/docs/install/lin/docker.md
- website/docs/install/mac/docker.md
- website/docs/install/win/docker.md
This PR adds the `--rpc-host=0.0.0.0` and --monitoring-host=0.0.0.0` instructions to running with docker
> Added monitoring host and rpc host to docker instructions

- .github/workflows/link-checker.yml
Basic link checker Github Action workflow.
It's set to ignore #! links used in the sidebar navigation.
> Github Action to check broken links

- nginx.conf
Search engines are indexing /docs/docs subpaths which lead to broken links. This PR adds a robots.txt entry to our nginx config to disallow such path from all user agents.
> Add Robots.txt to Disallow Old Docs Path

- website/docs/prysm-usage/parameters.md
Option to override the grpc host parameter from 127.0.0.1 to make it available to access from the remote client without having to proxy the listening port.
> missing in doc : grpc gateway host parameter

- website/docs/install/lin/docker.md
- website/docs/install/mac/docker.md
- website/docs/install/win/docker.md
Users running the beacon node with default docker parameters should be using --rpc-host=0.0.0.0 and --monitoring-host=0.0.0.0, this PR adds the following flags
> Add RPC Host and Monitoring Host to Docker Instructions

- website/docs/faq.md
- website/docs/prysm-usage/parameters.md
- website/docs/prysm-usage/secure-grpc.md
- website/docs/prysm-usage/wallet-keymanager.md
- website/docs/wallet/deterministic.md
- website/docs/wallet/introduction.md
- website/docs/wallet/nondeterministic.md
- website/docs/wallet/remote.md
- website/sidebars.json
This PR starts the required documentation for Prysm's accounts-v2 revamp, including new ways of generating wallets, accounts, and more. This PR will be the feature branch used to include all accounts-v2 docs before we push to production.
> Accounts V2 Documentation

- website/docs/testnet/medalla.md
When people would copy & paste the docker command the shell would not be able to process it without the right line breaks.
> Fixed line break on command

- website/docs/testnet/medalla.md
Previous PR #205 fixed this for the Mac tab. I though it would share this with the Linux version of the documentation, because it's the same command. This now fixes the same issue in the Linux documentation.
> Fix command line break for Linux tab

- website/docs/testnet/medalla.md
The script does not run without the newline characters.
Note that I was easily able to setup an Eth2.0 Medala validator node by using this Dockerfile that I created https://github.com/ethereum/eth2.0-deposit-cli/pull/83, along with your Docker instructions.
> Update medalla.md with missing newlines

- website/docs/prysm-usage/monitoring/grafana-dashboard.md
- website/static/assets/grafana-dashboards/big_amount_validators.json
- website/static/assets/grafana-dashboards/small_amount_validators.json
Feature proposed by [ncitron](https://github.com/ncitron)
- update the 2 dashboards to add the slasher memory usage + some quick modifications
- update the documentation to change some steps in order to retrieve the slasher metrics into grafana
Note: eth1 node is still to be done
> Add slasher hardware usage into prysm grafana dashboards

- website/docs/testnet/medalla.md
Removes the passwords directory from the docker-specific instructions as it is no longer used.
Also:  change step 5 to instruct users not to start a beacon node if already running from step 1.
> Remove prysm-wallet-v2-passwords from docker validator instructions

- website/docs/prysm-usage/running-a-validator.md
This is related to issue #213 .
In the Windows examples, %APPDATA% should be used as it points to APPDATA\roaming whereas the current %LOCALAPPDATA% points to APPDATA\local.  \roaming is the default location of the wallet.
In the Linux examples, the name of the folder should be .eth2validators
Also expand upon the --wallet-password-file tip.
Also fix tiny spelling error ('friendlist' -> 'friendliest')
> Fix names for wallet directories in running-a-validator

- website/docs/prysm-usage/monitoring/grafana-dashboard.md
Fixes issues with `localhost` links (although this is not the cleanest of solutions) and changes some absolute links to relative ones.
> Modify links on grafana-dashboard page

- website/docs/install/install-with-bazel.md
- website/docs/install/install-with-docker.md
- website/docs/install/install-with-script.md
- website/docs/prysm-usage/parameters.md
- website/docs/testnet/medalla.md
- website/docs/testnet/zinken.md
Fixes #246, fixes #243 
Currently, we do not force users to add --http-web3provider to their beacon node in our docs. This PR changes this and adds a link to how to setup an eth1 node. Additionally, we change the order of recommended steps to join the testnet to recommend syncing a beacon node _first_, and then going through the launchpad process. This PR also gets rid of deprecated options in the parameters page
> Enforce Eth1 Endpoint in Docs + Ordering of Node Syncing

- website/docs/prysm-usage/eth1-nodes.md
- website/docs/prysm-usage/slasher.md
- website/docs/wallet/exiting-a-validator.md
This PR includes several misc improvements to docs such as:
- Fixing the install link for go-ethereum
- Clarifying that slasher can be a resource hog and to be aware of risks during times of no finality
- Clarify the exiting a validator phrase. Some stakers were having trouble seeing it when using dark mode in their browsers
> Miscellaneous Docs Improvements

- website/docs/install/install-with-bazel.md
- website/docs/install/install-with-docker.md
- website/docs/install/install-with-script.md
- website/docs/testnet/medalla.md
- website/docs/testnet/zinken.md
This PR clarifies the format of the --http-web3provider flag for Prysm beacon nodes, mentioning it must be an http or an ipc endpoint
> Clarify Format of Eth1 Node Endpoints

- website/docs/faq.md
- website/docs/install/arm.md
- website/docs/install/install-with-bazel.md
- website/docs/install/install-with-docker.md
- website/docs/install/install-with-script.md
In light of the difficulties nodes face during the current low participation in the Medalla testnet, we have opted for increasing our recommended RAM to 16GB and a minimum of 8Gb for nodes
> Up the Resource Requirement Recommendations

- website/docs/how-prysm-works/beacon-node.md
Minor spelling correction found in the beacon-node documentation.  responsibile -> responsible
> Minor spelling correction in beacon-node doc

- website/static/assets/grafana-dashboards/big_amount_validators.json
- website/static/assets/grafana-dashboards/small_amount_validators.json
Since prysm beacon node has changed the name of some metrics, here is the update needed in order to fetch the right metrics for the dashboard.
Metrics that has been replaced:
`total_voted_target_balances` => `beacon_prev_epoch_target_gwei`
`total_eligible_balances` => `beacon_prev_epoch_active_gwei`
> Update the dashboard with the new metrics

- website/docs/mainnet/joining-eth2.md
- website/docs/prysm-usage/web-interface.md
- website/docs/testnet/medalla.md
Currently several bazel instructions for running Prysm result in an error related to an unrecognized parameter, as the `--` terminator is not correctly included in all cases. This PR should fix that.
> Fixes parameters in bazel instructions

- website/docs/prysm-usage/parameters.md
This PR adds all the flags we've had missing on our documentation for the validator and slasher clients. Mostly focusing around accounts management for the validator.
> Add all missing validator and slasher flags to docs

- website/docs/prysm-usage/parameters.md
Remove following invalid parameters:
- --slasher-tls-cert
- --slasher-rpc-provider
> Remove invalid parameters of 'beacon-chain' command

- website/docs/prysm-usage/web-interface.md
SSH Local Port Forwarding requires the 3500 port to get the beacon data otherwise it will fail.
> Update exposing the beacon port

- website/docs/how-prysm-works/ethereum-2.0-public-api.md
- website/docs/prysm-usage/database-backups.md
- website/docs/prysm-usage/eth1-nodes.md
- website/docs/prysm-usage/staying-up-to-date.md
- website/sidebars.json
This PR adds the following highly requested documentation:
> Update Documentation Popular Requests

- website/docs/prysm-usage/web-interface.md
With v1.1.0 of Prysm, the web ui has been greatly simplified, allowing for a single configuration of host:port to use prysm web
> Update Web UI Docs to Match v1.1.0 of Prysm

- website/docs/install/install-with-bazel.md
The documentation does not state running it from the default branch. The default `prysm` branch is `develop` and I was told never running it from develop. Updated that part to make it clearer since many on eth2staker community are running it off bazel.
> When running from source, state the tag instead

- website/docs/prysm-usage/monitoring/grafana-dashboard.md
- website/docs/prysm-usage/parameters.md
Adds the monitoring host option to our documentation params, fixes #218
> Add Monitoring Host to Params

- website/docs/devtools/block-explorers.md
This PR is an alternative to #308 which specifically lists mirrors of original block explorers under their own section. Now that Redot fulfilled all the requirements of proper attribution, there is no reason for us to not list open source mirrors in our documentation portal.
> Add Open Source Mirrors of Beaconcha.in

- website/docs/prysm-usage/graffiti-file.md
This should only be merged once https://github.com/prysmaticlabs/prysm/pull/8482 has been released in the next version.
I was unable to generate the `Example output` image, but perhaps they should all be changed to text only? Alternatively someone else could generate a similar styled image for me.
> Add `Ordered` description to graffiti-file

- website/docs/contribute/contribution-guidelines.md
Following current go build instructions will result in logs like
```
slasher/db/testing/setup_db.go:15:30: t.TempDir undefined (type testing.TB has no field or method TempDir)
note: module requires Go 1.16
```
> minor: use go 1.16 in contribution guidelines

- website/docs/reading/eth2.md
- Added new links
- Replaced outdated links
- Removed a few links:
- Ethereum Beige Paper - I started reading this ans it's all over the place. In my opinion the author did not have much knowledge about Ethereum. I think it will be better to not include this.
- How Does the P2P on Ethereum Work? - I replaced this with link to lib2p2
- How Does Kademlia Work? - we don't use Kademlia anymore
- Kademlia Protocol - we don't use Kademlia anymore
- Ethereum client implementations - it was outdated so I replaced it with a link to the offical wiki
> Update 'ETH2 Resources' page

- website/docs/install/install-with-bazel.md
- website/docs/install/install-with-docker.md
- website/docs/reading/bazel.md
This PR includes detailed instructions for building Prysm's docker images from source using Bazel, as well as fixes to pinned dependencies and better information for anyone attempting this
> Add Bazel Instructions for Docker

- website/docs/prysm-usage/client-stats.md
> Add a warning to the client stats page to communicate that the client-stats functionality is in an alpha testing stage

- website/docs/devtools/net-design.md
The p2p wiki includes a `Work Estimates` section that clearly is from another document.
> Remove the `Work Estimates` section from p2p wiki

- website/docs/prysm-usage/database-backups.md
To issue a backup, the directory must be in `0700` or it will return the following error in the logs:
```
"dir already exists without proper 0700 permissions"
```
> Docs: Add directory permissions for Database Backups

- website/docs/contribute/contribution-guidelines.md
Some of the commands listed in the Contribution Guide are outdated - namely:
1. Some of the paths have `cmd/` or `testing/` prefixed to them
2. `go test ./...` fails, since many tests rely on bazel.
I've taken some artistic freedom regarding point No. 2. Let me know if you want this delt with another way.
I have also moved the "Adding dependencies" to after the bazel section. 
Formerly it was between the "Running" and "Running with bazel" sections, which didn't make too much sense.
> Correct commands and paths in Contribution Guidelines

- website/docusaurus.config.js
- website/sidebars.json
- website/versioned_docs/version-2.0.0/devtools/api-middleware.md
- website/versioned_sidebars/version-2.0.0-sidebars.json
Adds a wiki page for the API Middleware. This page should be available only on v2. 1.x.x does not contain the latest version of the middleware, meaning that the docs will be out of sync.
> API Middleware dev wiki page

- website/docs/install/install-with-bazel.md
- website/docs/install/install-with-docker.md
- website/docs/install/install-with-script.md
- website/versioned_docs/version-2.0.0/install/install-with-bazel.md
- website/versioned_docs/version-2.0.0/install/install-with-docker.md
- website/versioned_docs/version-2.0.0/install/install-with-script.md
This fixes our documentation to link to the file directly rather than simply the github page which hosts it.
> Change Link to Directly Reference Genesis File

- website/versioned_docs/version-2.0.3/prysm-usage/staying-up-to-date.md
Linux should use `export` not `set` for env variable
> docs: Fix linux docs for downgrading

- website/versioned_docs/version-2.0.3/prysm-usage/staying-up-to-date.md
The documentation didn't show how to downgrade systemd service and a lot of users were having problems. This hopefully makes it clearer.
> docs: Update the downgrade documentation for systemd

- website/docs/prysm-usage/individual-validator-monitoring.md
- website/sidebars.json
Thanks to @potuz and @terencechain for the docs, we will soon have validator monitoring available in Prysm beacon nodes within the next release. This PR adds docs for the feature prepared by Potuz. To make them available upon release, a new docs version for the release tag must also be tagged and pushed to master.
> Add Validator Monitoring Docs from Potuz

- website/docs/devtools/init-state.md
- website/versioned_docs/version-1.x.x/wallet/slashing-protection.md
- website/versioned_docs/version-2.0.0/wallet/slashing-protection.md
- website/versioned_docs/version-2.0.3/devtools/init-state.md
- website/versioned_docs/version-2.0.3/reading/eth2.md
- website/versioned_docs/version-2.0.3/wallet/slashing-protection.md
pyrmont is no longer used and should be removed from our latest docs as a recommended testnet environment. replaced with prater.
> removing pyrmont from latest docs

- website/docs/install/install-with-docker.md
- website/docs/install/install-with-script.md
- website/versioned_docs/version-2.0.0/install/install-with-docker.md
- website/versioned_docs/version-2.0.0/install/install-with-script.md
- website/versioned_docs/version-2.0.3/install/install-with-docker.md
- website/versioned_docs/version-2.0.3/install/install-with-script.md
Was renamed from https://github.com/eth2-clients to https://github.com/eth-clients
> Updating URL for eth-clients

- website/docs/prysm-usage/web-interface.md
- website/versioned_docs/version-2.0.6/prysm-usage/web-interface.md
adding a new tip to the current version of the docs for web interface to address some confusion around auth token generation and reset. the token should be located inside the wallet location otherwise it will not work.
> Web Interface Doc: new tip for confusing auth token generation

- website/docs/contribute/prysms-golang-principles.md
- website/versioned_docs/version-1.x.x/contribute/prysms-golang-principles.md
- website/versioned_docs/version-2.0.0/contribute/prysms-golang-principles.md
- website/versioned_docs/version-2.0.3/contribute/prysms-golang-principles.md
- website/versioned_docs/version-2.0.6/contribute/prysms-golang-principles.md
Was probably a copy/paste error.
The good example still have the "BAD" comment.
https://docs.prylabs.network/docs/next/contribute/golang-principles/#error-handling
> Fix comment in good example in error handling

- website/docs/how-prysm-works/keymanager-api.md
- website/sidebars.json
Prysm will begin supporting the keymanager APIs in the next release https://github.com/ethereum/keymanager-APIs. We wanted to have a page to share information about our support for this feature.
> keymanager apis docs

- website/docs/execution-node/fee-recipient.md
the file example for fee recipient file format was wrongly formatting resulting in user confusion. removing commas is the fix.
> Fee-recipient: file example typo ( unnecessary commas) 

- website/docs/execution-node/fee-recipient.md
- website/versioned_docs/version-2.1.0/execution-node/fee-recipient.md
there are some bad examples on the page around the flag usage that should use 2 dashes not 1.
> fee-recipient: fixing bad examples

- website/docs/faq.md
- website/sidebars.json
- website/versioned_docs/version-2.1.0/faq.md
- website/versioned_sidebars/version-2.1.0-sidebars.json
This PR applies the following changes to vNext docs:
1. Move the FAQ out of the troubleshooting node and into the root of the TOC to improve discoverability, and to align more with the content since it's no longer a troubleshooting-only FAQ.
2. Some minor editorial improvements for a handful of questions - still needs work but I'm just boyscouting a bit
3. Add a question + answer about finding your account balance per @nisdas 
If we like how this feels as vNext, I'll pull into vCurrent and publish.
> FAQ Improvements (vNext only)

- website/docs/getting-started.md
- website/sidebars.json
This PR reintroduces the "Getting Started" content. It was originally removed as part of the vNext quickstart, but navigating to vNext from vCurrent Getting Started results in the sidebar disappearing. 
We recently aligned on keeping this page within vNext and turning it into a more informative / beginner-friendly introduction to Prysm. So this file will remain - content will change after vNext is published as vCurrent.
> Getting started fix

- website/sidebars.json
This page no longer reflects our content patterns and standards. Removing from sidebar for now - will remove file entirely when serverside redirects are configured. 
We don't get much contribution volume for docs - we can help contributions snap to standards on a case-by-case basis, and we can publish our latest standards when there's demand for them.
> Removing documentation standards from sidebar

- website/docs/execution-node/fee-recipient-vNext.md
There are some breaking changes listed in [this pr](https://github.com/prysmaticlabs/prysm/pull/11057) related to validator registration configs, there will continue to be changes to this as we continue to stabilize MEV builder configs. 
**Note: do not merge until associated PR is merged**
> Fee Recipient: validator registration update

- website/docs/install/install-with-script.md
The footnotes were nice when we didn't have supporting content, but the [Nodes and Networks](https://docs.prylabs.network/docs/concepts/nodes-networks) doc carries a lot of the onboarding weight now.
> Simplifying quickstart - removing footnotes

- website/docs/install/install-with-script.md
- website/docs/partials/_jwt-generation-partial.md
- website/docs/vNext/214-rc.md
- Updates embeddable JWT guidance to clarify that JWT is only needed if you're not running on Mainnet.
- Removes duplicated environment variable step from quickstart.
> JWT clarifications

- website/docs/execution-node/fee-recipient-vNext.md
Updating the gas_limit type to string(uint64) instead of being a number
This is related to changes in the PRs below
https://github.com/prysmaticlabs/prysm/pull/11264
fixes #11258
> Fee Recipient : updating gas_limit type

- website/docs/prysm-usage/checkpoint-sync.md
previous pr removed the `@lastest` tag on the `go run` command for prysmctl. This just restores it.
> restore latest tag to prysmctl command

- website/docs/prysm-usage/checkpoint-sync.md
prysm's go.mod contains `replace` directives which makes it not installable via `go run` or `go install` when specifying a git hash/tag (ie `@latest`). We will soon have a binary release which will allow installation via prysm.sh or downloading from github, but in the meantime we need to instruct users to clone the repository to run `prysmctl`.
> add instructions for cloning git to run prysmctl

- website/docs/prysm-usage/checkpoint-sync.md
nishant recommended we change our url for checkpoint sync public beacon nodes
> updating the checkpoint sync urls

- website/docs/prysm-usage/prysmctl.md
note that windows users should use binaries
> Prysmctl: clarifications on execution and windows user

- website/docs/advanced/proof-of-stake-devnet.md
Add the `contract-deployment-block=0` to the guide as requested in the DC local setup discussion [here](https://discord.com/channels/476244492043812875/560308336248225812/1092729846876082258).
> Add contract-deployment-block flag

- README.md
- website/docs/concepts/nodes-networks.md
- website/docs/getting-started.md
- website/docs/install/install-with-bazel.md
- website/docs/install/install-with-docker.md
- website/docs/install/install-with-script.md
- website/docs/install/partials/_quickstart-install-prysm.md
- website/docs/install/partials/_quickstart-intro.md
- website/docs/install/partials/_quickstart-prereqs.md
- website/docs/install/partials/_quickstart-run-beacon-node.md
- website/docs/install/partials/_quickstart-run-execution-node.md
- website/docs/install/partials/_quickstart-run-validator.md
- website/docs/monitoring/partials/_status-checklist-partial.md
- website/docs/partials/_jwt-generation-partial.md
- website/docs/partials/_multidimensional-content-controls-partial.md
- website/docs/prysm-usage/checkpoint-sync.md
- website/docs/security-best-practices.md
- website/src/components/MultiDimensionalContentWidget.js
**Main changes:**
- Geth:
- Remove the usage of the `Geth installer` as it seems not to be maintained any more. (Or at least I did not find it on Geth download page.)
- Explicitly set the IPC file location, as the default location created by Geth does not match what the documentation currently use in the Prysm BN command line for MacOS.
- Nethermind:  
- Explicitly set the IPC file location
- Add win/others cases  
- Replace usage of `Goerli-Prater` by `Goerli` since even the EF https://prater.launchpad.ethereum.org/en/ redirects to  https://goerli.launchpad.ethereum.org/en/ without any mention of the word `prater`. (However, added a note to explained why the `genesis.ssz` file is still located under the `prater` directory.
- Add usage of `--suggested-fee-recipient` option in the Prysm VC …
> Improve quickstart

- website/docs/how-prysm-works/validator-lifecycle.md
I think clarifying what an eek is would be helpful. As I was updating the page, I found that there are double spaces here and there, I think this may be a typo so I updated the page for this as well.
> enh(validator-lifecycle): clarify eek and drop double spaces

- website/docs/how-prysm-works/validator-lifecycle.md
Noticed while reading https://docs.prylabs.network/docs/how-prysm-works/validator-lifecycle
> Fix typo in validator-lifecycle.md

- website/docs/advanced/proof-of-stake-devnet.md
- website/docs/how-prysm-works/ethereum-public-api.md
- website/docs/how-prysm-works/prysm-public-api.md
- website/docs/install/install-with-docker.md
- website/docs/prysm-usage/web-interface.md
grpc gateway will be deprecated in the next release, flag names are updated in docs, old alias can still be used. 
related to https://github.com/prysmaticlabs/prysm/pull/14089
> grpc gateway deprecated, update flags in doc

- website/docs/install/install-with-docker.md
- website/docs/monitoring/partials/_status-checklist-partial.md
missed changes on v5.1.1 we should direct users to use the standard APIs.
addresses https://github.com/prysmaticlabs/prysm/issues/14543
note this issue has not been resolved at the time of this PR: https://github.com/prysmaticlabs/prysm/issues/14226
> monitoring: updating docs to use standard apis

- website/docs/how-prysm-works/prysm-public-api.md
gRPC page should have removed json mapping information after v5.1.1 this was a miss on documentation updates.
> updating grpc page due to gateway removal

- website/docs/contribute/bugreports.md
The word "catagories" should be spelled as "**categories**."
Corrected.
> Typo Update bugreports.md

- website/docs/devtools/end-to-end.md
- website/docs/wallet/web3signer.md
This pull request contains changes to improve clarity, correctness and structure.
**Description correction:**
Corrected "ran" to "run" - the correct form of the verb is used in the passive voice.
Corrected "consist" to "consists" - the error in subject-verb agreement in the singular has been corrected.
Also, "with" was added in the sentence where it is better to use it for correct grammatical structure
Please review the changes and let me know if any additional changes are needed.
> fix: typos in documentation files

- docs/prysm-usage/database-backups.md
- Removed references to performing a backup while client is running
- Searched cursory terms/language
- Searched for code refs
- Added emphasis to the warning about not running client while backing up
> docs: removing-live-backup-refs

- docs/configure-prysm/sync-from-a-checkpoint.md
- source: https://github.com/OffchainLabs/prysm-documentation/issues/1108
- Update the description of --checkpoint-sync-url and --genesis-beacon-api-url in the "Configure checkpoint sync via network request" section.
> docs: update sync-from-checkpoint.md file
